### ISSUE TITLE
Import by 25 words

### ISSUE THREAD

**Issue by pepa65** [scholtz/wallet#10]
I have an existing wallet that I only have 25 words for, and I don't think there is a way to import into A-Wallet that way. How would I go about converting those to a file that can be imported?

Is this something that could be added, importing by 25 words??

Anyway this is an important and amazing app! Thanks for contributing this.

**Comment by scholtz** [comment]
yes, you can import mnemonic to AWallet.. just go to new account, import account.

actually what you have is the account not the wallet.. the account is the specific account and some people wrongly name it the wallet.. the wallet is the storage of several accounts.

so you should first create a wallet with your strong password protection, and then you can import existing accounts into it or create new accounts

**Comment by pepa65** [comment]
OK, first create a new wallet, and then import the account!
Very nice, you even have the vanity-address hunter built in.
