### ISSUE TITLE
JavaScript Error Still Showing Even After Enabling JavaScript

### ISSUE THREAD

**Issue by 0xLiquidGlass** [scholtz/wallet#44]
This was the message that I received:

"We're sorry but wallet doesn't work properly without JavaScript enabled. Please enable it to continue."

This message this still shows up even after JavaScript was enabled on my browser

Link: https://main.h3.a-wallet.net/

**Comment by scholtz** [comment]
Strange, it is in the section <noscript>

```
<noscript><strong>We're sorry but wallet doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript>
```

https://www.w3schools.com/TAGs/tag_noscript.asp

To my knowledge it is shown to user only if the javasciprt is disabled.

Are there any errors in console? Can you try refresh the page?

**Comment by 0xLiquidGlass** [comment]
Sorry for the late reply
I tried to go to https://main.h3.a-wallet.net/ again and it worked as expected today
I think it was because I did not refresh the site properly yesterday
